# Constraints file for the Basys 3 FPGA development card

# Onboard crystal
set_property PACKAGE_PIN W5 [get_ports FPGA_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_CLK]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports FPGA_CLK]

# Reset (centre button)
set_property PACKAGE_PIN U18 [get_ports FPGA_nRESET]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_nRESET]

# Switches
set_property PACKAGE_PIN V17 [get_ports {SW[0]}]
set_property PACKAGE_PIN V16 [get_ports {SW[1]}]
set_property PACKAGE_PIN W16 [get_ports {SW[2]}]
set_property PACKAGE_PIN W17 [get_ports {SW[3]}]
set_property PACKAGE_PIN W15 [get_ports {SW[4]}]
set_property PACKAGE_PIN V15 [get_ports {SW[5]}]
set_property PACKAGE_PIN W14 [get_ports {SW[6]}]
set_property PACKAGE_PIN W13 [get_ports {SW[7]}]
set_property PACKAGE_PIN V2 [get_ports {SW[8]}]
set_property PACKAGE_PIN T3 [get_ports {SW[9]}]
set_property PACKAGE_PIN T2 [get_ports {SW[10]}]
set_property PACKAGE_PIN R3 [get_ports {SW[11]}]
set_property PACKAGE_PIN W2 [get_ports {SW[12]}]
set_property PACKAGE_PIN U1 [get_ports {SW[13]}]
set_property PACKAGE_PIN T1 [get_ports {SW[14]}]
set_property PACKAGE_PIN R2 [get_ports {SW[15]}]

set_property IOSTANDARD LVCMOS33 [get_ports {SW[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW[15]}]

# LEDs
set_property PACKAGE_PIN U16 [get_ports {LED_DEBUG[0]}]
set_property PACKAGE_PIN E19 [get_ports {LED_DEBUG[1]}]
set_property PACKAGE_PIN U19 [get_ports {LED_DEBUG[2]}]
set_property PACKAGE_PIN V19 [get_ports {LED_DEBUG[3]}]
set_property PACKAGE_PIN W18 [get_ports {LED_DEBUG[4]}]
set_property PACKAGE_PIN U15 [get_ports {LED_DEBUG[5]}]
set_property PACKAGE_PIN U14 [get_ports {LED_DEBUG[6]}]
set_property PACKAGE_PIN V14 [get_ports {LED_DEBUG[7]}]
set_property PACKAGE_PIN V13 [get_ports {LED_DEBUG[8]}]
set_property PACKAGE_PIN V3 [get_ports {LED_DEBUG[9]}]
set_property PACKAGE_PIN W3 [get_ports {LED_DEBUG[10]}]
set_property PACKAGE_PIN U3 [get_ports {LED_DEBUG[11]}]
set_property PACKAGE_PIN P3 [get_ports {LED_DEBUG[12]}]
set_property PACKAGE_PIN N3 [get_ports {LED_DEBUG[13]}]
set_property PACKAGE_PIN P1 [get_ports {LED_DEBUG[14]}]
set_property PACKAGE_PIN L1 [get_ports {LED_DEBUG[15]}]

set_property IOSTANDARD LVCMOS33 [get_ports {LED_DEBUG[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_DEBUG[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_DEBUG[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_DEBUG[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_DEBUG[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_DEBUG[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_DEBUG[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_DEBUG[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_DEBUG[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_DEBUG[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_DEBUG[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_DEBUG[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_DEBUG[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_DEBUG[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_DEBUG[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_DEBUG[15]}]

# Pmod Header JB - RGB Signals
set_property PACKAGE_PIN A14 [get_ports G1]
set_property PACKAGE_PIN A16 [get_ports B1]
set_property PACKAGE_PIN B15 [get_ports G2]
set_property PACKAGE_PIN B16 [get_ports B2]
set_property PACKAGE_PIN A15 [get_ports R1]
#set_property PACKAGE_PIN A17 [get_ports {  }]
set_property PACKAGE_PIN C15 [get_ports R2]
#set_property PACKAGE_PIN C16 [get_ports {  }]

set_property IOSTANDARD LVCMOS33 [get_ports R1]
set_property IOSTANDARD LVCMOS33 [get_ports R2]
set_property IOSTANDARD LVCMOS33 [get_ports G1]
set_property IOSTANDARD LVCMOS33 [get_ports G2]
set_property IOSTANDARD LVCMOS33 [get_ports B1]
set_property IOSTANDARD LVCMOS33 [get_ports B2]
#set_property IOSTANDARD LVCMOS33 [get_ports {  }]
#set_property IOSTANDARD LVCMOS33 [get_ports {  }]

# Pmod Header JC - Address and Control Signals
set_property PACKAGE_PIN K17 [get_ports B]
set_property PACKAGE_PIN M18 [get_ports D]
set_property PACKAGE_PIN N17 [get_ports LAT]
set_property PACKAGE_PIN P18 [get_ports OE]
set_property PACKAGE_PIN L17 [get_ports A]
set_property PACKAGE_PIN M19 [get_ports C]
set_property PACKAGE_PIN P17 [get_ports BCLK]
#set_property PACKAGE_PIN R18 [get_ports {  }]

set_property IOSTANDARD LVCMOS33 [get_ports A]
set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property IOSTANDARD LVCMOS33 [get_ports C]
set_property IOSTANDARD LVCMOS33 [get_ports D]
set_property IOSTANDARD LVCMOS33 [get_ports BCLK]
set_property IOSTANDARD LVCMOS33 [get_ports LAT]
set_property IOSTANDARD LVCMOS33 [get_ports OE]
#set_property IOSTANDARD LVCMOS33 [get_ports {  }]

set_property MARK_DEBUG false [get_nets {led_display_driver_inst/pixel_counter[6]_i_3_n_0}]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list FPGA_CLK_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {led_display_driver_inst/led_display_phy_inst/bclk_buf[0]} {led_display_driver_inst/led_display_phy_inst/bclk_buf[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list B2_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list BCLK_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list G2_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list led_display_driver_inst/phy_enable]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list led_display_driver_inst/phy_ready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list R2_OBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets FPGA_CLK_IBUF_BUFG]
